### PR TITLE
Made awesome compliant

### PR DESCRIPTION
**Pull request by DanielMSchmidt**
Hi,

Awesome list. To have this visible for more people, I thought it would be great to be included in the main awesome list. 
This PR aims to make this awesome list compliant. (https://github.com/sindresorhus/awesome/pull/660)

Hope this helps, have a nice day!

### CODE REVIEW

**Comment by DanielMSchmidt** [comment]
Sorry that this PR was unannounced and got so big, I just wanted to add this to the awesome list of awesome lists and didn't think about the consequences for this project. This PR relates to sindresorhus/awesome#660

**Comment by jdrgoms** [comment]
Congratulations and thank you very much for your contributions @DanielMSchmidt  :smile:

**Comment by DanielMSchmidt** [comment]
Great, nice to hear 👍

**Comment by jdrgoms** [comment]
@DanielMSchmidt do you have twitter?

**Comment by DanielMSchmidt** [comment]
Yes, [DSchmidt1992](https://twitter.com/DSchmidt1992).

**Pull request merged**
